### ISSUE TITLE
Support starting with `大字` or `字` Ooaza address search

### ISSUE THREAD

**Issue by sanak** [mbasa/pgGeocoder#17]
@mbasa Sometimes Ooaza string starts with `大字` or `字` words.
[大字 - Wikipedia](https://ja.wikipedia.org/wiki/%E5%A4%A7%E5%AD%97)

Those are also used when searching address, so adding both to additional Ooaza normalization process will be nice.
For output, following original ISJ (or ABR) data as it is will be enough, I think.

```psql
# SELECT COUNT(*) FROM pggeocoder.address_o WHERE ooaza LIKE '大字%';
 count 
-------
 10698
(1 row)
```
```psql
# SELECT COUNT(*) FROM pggeocoder.address_o WHERE ooaza LIKE '字%';
 count 
-------
  8007
(1 row)
```

**Comment by mbasa** [comment]
pgGeocoder can easily match addresses that contains or starts with `大字`  and `字`. The problem is sometimes the written addresses **omits** these characters, when they should be included to get a match. 

The fix here is to handle the problem in the normalizing process as mentioned.

**Comment by sanak** [comment]
@mbasa Sorry, I forgot to mention here, but about `千葉県流山市鰭ケ崎` address case, both `大字鰭ケ崎` and `鰭ケ崎` address seem to exist at least about 3 years ago.
https://ja.wikipedia.org/wiki/%E9%B0%AD%E3%82%B1%E5%B4%8E
> **鰭ケ崎**（ひれがさき）は、[千葉県](https://ja.wikipedia.org/wiki/%E5%8D%83%E8%91%89%E7%9C%8C)[流山市](https://ja.wikipedia.org/wiki/%E6%B5%81%E5%B1%B1%E5%B8%82)の地名。町である地番整理施行地区（**鰭ケ崎**）と、大字である未施行地区（**大字鰭ケ崎**）があるが、本項目では両方取り上げる。

https://www.city.nagareyama.chiba.jp/_res/projects/default_project/_page_/001/029/625/zyusyo-hireomo.pdf
```sql
SELECT * FROM pggeocoder.address_o
WHERE
  todofuken = '千葉県' AND
  shikuchoson = '流山市' AND
  ooaza LIKE '%鰭ケ崎%';

 todofuken | shikuchoson | tr_shikuchoson |    ooaza     |  tr_ooaza  |    lat    |    lon     |     code     |                        geog                        
-----------+-------------+----------------+--------------+------------+-----------+------------+--------------+----------------------------------------------------
 千葉県    | 流山市      | 流山市         | 大字鰭ケ崎   | 大字鰭が埼 | 35.841674 | 139.912205 | 122200024000 | 0101000020E6100000ED478AC8307D61405EF23FF9BBEB4140
 千葉県    | 流山市      | 流山市         | 鰭ケ崎       | 鰭が埼     | 35.839606 | 139.908472 | 122200043000 | 0101000020E61000009D2ADF33127D614040C39B3578EB4140
```

So, normalizing (cutting of) `大字` or `字` cause trouble in such case, because duplicate rows will be generated...

**Comment by sanak** [comment]
@mbasa This is just my idea, but how about the following process ?
1. Search input address as it is.
   * `千葉県流山市大字鰭ケ崎` => return above 1st row.
   * `千葉県流山市鰭ケ崎` => return above 2nd row.
2. If No.1 doesn't hit, and input address starts with `大字` or `字`, then try to search with cutting of `大字` or `字` only from input address (not from `address_o` table side).

**Comment by sanak** [comment]
@mbasa Well, with above commit (https://github.com/mbasa/pgGeocoder/commit/2b4a2d952568da16eb7810f990cc3835744395f8), now normalized `tr_ooaza` becomes both `鰭が埼`,
```sql
SELECT * FROM pggeocoder.address_o
WHERE
  todofuken = '千葉県' AND
  shikuchoson = '流山市' AND
  ooaza LIKE '%鰭ケ崎%';
 todofuken | shikuchoson | tr_shikuchoson |    ooaza     | tr_ooaza |    lat    |    lon     |     code     |                        geog                        | year 
-----------+-------------+----------------+--------------+----------+-----------+------------+--------------+----------------------------------------------------+------
 千葉県    | 流山市      | 流山市         | 大字鰭ケ崎   | 鰭が埼   | 35.841674 | 139.912205 | 122200024000 | 0101000020E6100000ED478AC8307D61405EF23FF9BBEB4140 | 2023
 千葉県    | 流山市      | 流山市         | 鰭ケ崎       | 鰭が埼   | 35.839606 | 139.908472 | 122200043000 | 0101000020E61000009D2ADF33127D614040C39B3578EB4140 | 2023
 千葉県    | 流山市      | 流山市         | 鰭ケ崎一丁目 | 鰭が埼1- | 35.842741 | 139.910488 | 122200063001 | 0101000020E6100000D0ECBAB7227D6140C9FFE4EFDEEB4140 | 2023
 千葉県    | 流山市      | 流山市         | 鰭ケ崎二丁目 | 鰭が埼2- | 35.844799 | 139.909394 | 122200063002 | 0101000020E6100000B72572C1197D6140C558A65F22EC4140 | 2023
(4 rows)
```

and that seems to cause the current test failures. (It seems to return 1st row, although 2nd row is the best match.)
https://github.com/mbasa/pgGeocoder/actions/runs/9993699530/job/27621685878#step:9:32
```
# Failed test 443: "千葉県流山市鰭ケ崎１７６１－３"
#         have: {千葉県,流山市,大字鰭ケ崎}
#         want: {千葉県,流山市,鰭ケ崎}
# Failed test 444: "千葉県流山市鰭ケ崎４８７－１"
#         have: {千葉県,流山市,大字鰭ケ崎}
#         want: {千葉県,流山市,鰭ケ崎}
```

I will delete the case temporarily for release process, but it would be nice to be solved in future.
